// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p11
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:152

#ifndef _TAO_IDL_TWITTERTYPESUPPORTC_RCHNYB_H_
#define _TAO_IDL_TWITTERTYPESUPPORTC_RCHNYB_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "TwitterC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:38

namespace Twitter
{

  // TAO_IDL - Generated from
  // c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< Twitter::Tweet, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> TweetSeq;
  

  // TAO_IDL - Generated from
  // c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_TWITTER_TWEETTYPESUPPORT__VAR_OUT_CH_)
#define _TWITTER_TWEETTYPESUPPORT__VAR_OUT_CH_

  class TweetTypeSupport;
  typedef TweetTypeSupport *TweetTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        TweetTypeSupport
      >
    TweetTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        TweetTypeSupport
      >
    TweetTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  TweetTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef TweetTypeSupport_ptr _ptr_type;
    typedef TweetTypeSupport_var _var_type;
    typedef TweetTypeSupport_out _out_type;

    // The static operations.
    static TweetTypeSupport_ptr _duplicate (TweetTypeSupport_ptr obj);

    static void _tao_release (TweetTypeSupport_ptr obj);

    static TweetTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static TweetTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static TweetTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    TweetTypeSupport (void);

    

    virtual ~TweetTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    TweetTypeSupport (const TweetTypeSupport &);

    void operator= (const TweetTypeSupport &);
  };

  // TAO_IDL - Generated from
  // c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_TWITTER_TWEETDATAWRITER__VAR_OUT_CH_)
#define _TWITTER_TWEETDATAWRITER__VAR_OUT_CH_

  class TweetDataWriter;
  typedef TweetDataWriter *TweetDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        TweetDataWriter
      >
    TweetDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        TweetDataWriter
      >
    TweetDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  TweetDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef TweetDataWriter_ptr _ptr_type;
    typedef TweetDataWriter_var _var_type;
    typedef TweetDataWriter_out _out_type;

    // The static operations.
    static TweetDataWriter_ptr _duplicate (TweetDataWriter_ptr obj);

    static void _tao_release (TweetDataWriter_ptr obj);

    static TweetDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static TweetDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static TweetDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::Twitter::Tweet & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::Twitter::Tweet & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::Twitter::Tweet & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::Twitter::Tweet & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::Twitter::Tweet & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::Twitter::Tweet & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::Twitter::Tweet & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::Twitter::Tweet & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Twitter::Tweet & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Twitter::Tweet & instance_data) = 0;

    // TAO_IDL - Generated from
    // c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    TweetDataWriter (void);

    

    virtual ~TweetDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    TweetDataWriter (const TweetDataWriter &);

    void operator= (const TweetDataWriter &);
  };

  // TAO_IDL - Generated from
  // c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_TWITTER_TWEETDATAREADER__VAR_OUT_CH_)
#define _TWITTER_TWEETDATAREADER__VAR_OUT_CH_

  class TweetDataReader;
  typedef TweetDataReader *TweetDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        TweetDataReader
      >
    TweetDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        TweetDataReader
      >
    TweetDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  TweetDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef TweetDataReader_ptr _ptr_type;
    typedef TweetDataReader_var _var_type;
    typedef TweetDataReader_out _out_type;

    // The static operations.
    static TweetDataReader_ptr _duplicate (TweetDataReader_ptr obj);

    static void _tao_release (TweetDataReader_ptr obj);

    static TweetDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static TweetDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static TweetDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::Twitter::TweetSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::Twitter::TweetSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::Twitter::TweetSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::Twitter::TweetSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::Twitter::Tweet & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::Twitter::Tweet & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::Twitter::TweetSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::Twitter::TweetSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::Twitter::TweetSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::Twitter::TweetSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::Twitter::TweetSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::Twitter::TweetSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::Twitter::TweetSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::Twitter::TweetSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::Twitter::TweetSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Twitter::Tweet & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Twitter::Tweet & instance_data) = 0;

    // TAO_IDL - Generated from
    // c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    TweetDataReader (void);

    

    virtual ~TweetDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    TweetDataReader (const TweetDataReader &);

    void operator= (const TweetDataReader &);
  };

// TAO_IDL - Generated from
// c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:67

} // module Twitter

// TAO_IDL - Generated from
// c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_TWITTER_TWEETTYPESUPPORT__TRAITS_)
#define _TWITTER_TWEETTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::Twitter::TweetTypeSupport>
  {
    static ::Twitter::TweetTypeSupport_ptr duplicate (
        ::Twitter::TweetTypeSupport_ptr p);
    static void release (
        ::Twitter::TweetTypeSupport_ptr p);
    static ::Twitter::TweetTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Twitter::TweetTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_TWITTER_TWEETDATAWRITER__TRAITS_)
#define _TWITTER_TWEETDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::Twitter::TweetDataWriter>
  {
    static ::Twitter::TweetDataWriter_ptr duplicate (
        ::Twitter::TweetDataWriter_ptr p);
    static void release (
        ::Twitter::TweetDataWriter_ptr p);
    static ::Twitter::TweetDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Twitter::TweetDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_TWITTER_TWEETDATAREADER__TRAITS_)
#define _TWITTER_TWEETDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::Twitter::TweetDataReader>
  {
    static ::Twitter::TweetDataReader_ptr duplicate (
        ::Twitter::TweetDataReader_ptr p);
    static void release (
        ::Twitter::TweetDataReader_ptr p);
    static ::Twitter::TweetDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Twitter::TweetDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "TwitterTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

