// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p11
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:376


#include "TwitterTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "TwitterTypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Twitter::TweetTypeSupport.

Twitter::TweetTypeSupport_ptr
TAO::Objref_Traits<Twitter::TweetTypeSupport>::duplicate (
    Twitter::TweetTypeSupport_ptr p)
{
  return Twitter::TweetTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<Twitter::TweetTypeSupport>::release (
    Twitter::TweetTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

Twitter::TweetTypeSupport_ptr
TAO::Objref_Traits<Twitter::TweetTypeSupport>::nil (void)
{
  return Twitter::TweetTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Twitter::TweetTypeSupport>::marshal (
    const Twitter::TweetTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Twitter::TweetTypeSupport::TweetTypeSupport (void)
{}

Twitter::TweetTypeSupport::~TweetTypeSupport (void)
{
}

Twitter::TweetTypeSupport_ptr
Twitter::TweetTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return TweetTypeSupport::_duplicate (
      dynamic_cast<TweetTypeSupport_ptr> (_tao_objref)
    );
}

Twitter::TweetTypeSupport_ptr
Twitter::TweetTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return TweetTypeSupport::_duplicate (
      dynamic_cast<TweetTypeSupport_ptr> (_tao_objref)
    );
}

Twitter::TweetTypeSupport_ptr
Twitter::TweetTypeSupport::_nil (void)
{
  return 0;
}

Twitter::TweetTypeSupport_ptr
Twitter::TweetTypeSupport::_duplicate (TweetTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Twitter::TweetTypeSupport::_tao_release (TweetTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Twitter::TweetTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Twitter/TweetTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Twitter::TweetTypeSupport::_interface_repository_id (void) const
{
  return "IDL:Twitter/TweetTypeSupport:1.0";
}

::CORBA::Boolean
Twitter::TweetTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Twitter::TweetDataWriter.

Twitter::TweetDataWriter_ptr
TAO::Objref_Traits<Twitter::TweetDataWriter>::duplicate (
    Twitter::TweetDataWriter_ptr p)
{
  return Twitter::TweetDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<Twitter::TweetDataWriter>::release (
    Twitter::TweetDataWriter_ptr p)
{
  ::CORBA::release (p);
}

Twitter::TweetDataWriter_ptr
TAO::Objref_Traits<Twitter::TweetDataWriter>::nil (void)
{
  return Twitter::TweetDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Twitter::TweetDataWriter>::marshal (
    const Twitter::TweetDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Twitter::TweetDataWriter::TweetDataWriter (void)
{}

Twitter::TweetDataWriter::~TweetDataWriter (void)
{
}

Twitter::TweetDataWriter_ptr
Twitter::TweetDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return TweetDataWriter::_duplicate (
      dynamic_cast<TweetDataWriter_ptr> (_tao_objref)
    );
}

Twitter::TweetDataWriter_ptr
Twitter::TweetDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return TweetDataWriter::_duplicate (
      dynamic_cast<TweetDataWriter_ptr> (_tao_objref)
    );
}

Twitter::TweetDataWriter_ptr
Twitter::TweetDataWriter::_nil (void)
{
  return 0;
}

Twitter::TweetDataWriter_ptr
Twitter::TweetDataWriter::_duplicate (TweetDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Twitter::TweetDataWriter::_tao_release (TweetDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Twitter::TweetDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Twitter/TweetDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Twitter::TweetDataWriter::_interface_repository_id (void) const
{
  return "IDL:Twitter/TweetDataWriter:1.0";
}

::CORBA::Boolean
Twitter::TweetDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// c:\users\lashmawy\documents\soft\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Twitter::TweetDataReader.

Twitter::TweetDataReader_ptr
TAO::Objref_Traits<Twitter::TweetDataReader>::duplicate (
    Twitter::TweetDataReader_ptr p)
{
  return Twitter::TweetDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<Twitter::TweetDataReader>::release (
    Twitter::TweetDataReader_ptr p)
{
  ::CORBA::release (p);
}

Twitter::TweetDataReader_ptr
TAO::Objref_Traits<Twitter::TweetDataReader>::nil (void)
{
  return Twitter::TweetDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Twitter::TweetDataReader>::marshal (
    const Twitter::TweetDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Twitter::TweetDataReader::TweetDataReader (void)
{}

Twitter::TweetDataReader::~TweetDataReader (void)
{
}

Twitter::TweetDataReader_ptr
Twitter::TweetDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return TweetDataReader::_duplicate (
      dynamic_cast<TweetDataReader_ptr> (_tao_objref)
    );
}

Twitter::TweetDataReader_ptr
Twitter::TweetDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return TweetDataReader::_duplicate (
      dynamic_cast<TweetDataReader_ptr> (_tao_objref)
    );
}

Twitter::TweetDataReader_ptr
Twitter::TweetDataReader::_nil (void)
{
  return 0;
}

Twitter::TweetDataReader_ptr
Twitter::TweetDataReader::_duplicate (TweetDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Twitter::TweetDataReader::_tao_release (TweetDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Twitter::TweetDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Twitter/TweetDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Twitter::TweetDataReader::_interface_repository_id (void) const
{
  return "IDL:Twitter/TweetDataReader:1.0";
}

::CORBA::Boolean
Twitter::TweetDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

